services:
  # servicio de mysql
  biblioteca_mysql:
    image: mysql:8.0
    container_name: biblioteca_mysql
    restart: unless-stopped
    env_file:
      - .env
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - biblioteca_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # servicio backend con (FastAPI)
  biblioteca_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biblioteca_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      biblioteca_mysql:
        condition: service_healthy
    networks:
      - biblioteca_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # servicio frontend con (React + Vite) 
  biblioteca_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: biblioteca_frontend
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - biblioteca_network

      

volumes:
  mysql_data:
    driver: local

networks:
  biblioteca_network:
    driver: bridge